// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjZ-xRik5iCQ9vyZePHZ6GzV1SFJA7fsU',
    appId: '1:1018980842346:web:81dc5fb7c16a085c404313',
    messagingSenderId: '1018980842346',
    projectId: 'txiapp-project',
    authDomain: 'txiapp-project.firebaseapp.com',
    storageBucket: 'txiapp-project.appspot.com',
    measurementId: 'G-9TBMEHPZS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80eHCVBkN6wr5QSiOR5pxG5u-YoEzJyc',
    appId: '1:1018980842346:android:043bb6a373761579404313',
    messagingSenderId: '1018980842346',
    projectId: 'txiapp-project',
    storageBucket: 'txiapp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlcVV3fZuFaOn5f3d5CImVZuhBDCMENkk',
    appId: '1:1018980842346:ios:d5e1586e2cbbdb8c404313',
    messagingSenderId: '1018980842346',
    projectId: 'txiapp-project',
    storageBucket: 'txiapp-project.appspot.com',
    iosClientId: '1018980842346-e64efp7emakt8g4u2anjs6av1so4b3h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.txiapp',
  );
}
